"""place_created

Revision ID: 26fdb6d9659d
Revises: bd0cf10fc949
Create Date: 2023-09-29 20:46:33.959629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26fdb6d9659d'
down_revision: Union[str, None] = 'bd0cf10fc949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_place_email', table_name='place')
    op.drop_column('place', 'is_verified')
    op.drop_column('place', 'hashed_password')
    op.drop_column('place', 'email')
    op.drop_column('place', 'is_superuser')
    op.drop_column('place', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('place', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('place', sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=False))
    op.add_column('place', sa.Column('hashed_password', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    op.add_column('place', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index('ix_place_email', 'place', ['email'], unique=False)
    # ### end Alembic commands ###
