"""empty message

Revision ID: 272affa1c18e
Revises: 
Create Date: 2023-10-23 19:38:56.937847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '272affa1c18e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('verification_token', sa.String(), nullable=False))
    op.add_column('user', sa.Column('verification_token_expiration', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'verification_token_expiration')
    op.drop_column('user', 'verification_token')
    op.create_table('review',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('place_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], name='review_place_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='review_pkey')
    )
    op.create_table('place_image',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('place_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('photo_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('photo_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_verified_photo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], name='place_image_place_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='place_image_pkey')
    )
    op.create_table('place',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=320), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], name='place_creator_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='place_pkey'),
    sa.UniqueConstraint('title', name='place_title_key')
    )
    # ### end Alembic commands ###
