"""image add to user

Revision ID: 6a5e0a40244c
Revises: b597a2ff102a
Create Date: 2023-11-23 04:33:11.090067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a5e0a40244c'
down_revision: Union[str, None] = 'b597a2ff102a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['image'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'image')
    # ### end Alembic commands ###
