"""placeimage reviews

Revision ID: 6ba5146fddf9
Revises: 30feca3bf994
Create Date: 2023-09-30 02:23:31.915611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ba5146fddf9'
down_revision: Union[str, None] = '30feca3bf994'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('place_creator_id_fkey', 'place', type_='foreignkey')
    op.drop_column('place', 'creator_id')
    op.drop_constraint('review_creator_id_fkey', 'review', type_='foreignkey')
    op.drop_column('review', 'creator_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('review_creator_id_fkey', 'review', 'user', ['creator_id'], ['id'])
    op.add_column('place', sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('place_creator_id_fkey', 'place', 'user', ['creator_id'], ['id'])
    # ### end Alembic commands ###
