"""placeimage reviews

Revision ID: b9be1d3f0f2a
Revises: 71ecc2f6adcb
Create Date: 2023-09-30 02:03:55.406243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9be1d3f0f2a'
down_revision: Union[str, None] = '71ecc2f6adcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'review', 'user', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_column('review', 'creator_id')
    # ### end Alembic commands ###
